styco:
  image: styers/styco-site:latest
  # net: "host"
  ports:
  - "80:5000"
  - "3000:3000"
  - "3001:3001"
  - "35729:35729"
  volumes:
   - .:/opt/app/src
  env_file:
    - ./.env
  container_name: styco
# links:
# - mongo
# - redis
# mongo:
#  image: mongo:3.2.1
#   ports:
#     - "27017:27017"
#   container_name: mongo
# redis:
#   image: redis:3.0.6-alpine
#   ports:
#     - "6379:6379"
#   container_name: redis
